color: blue
day_night: true
pages:
  count: 12
header:
  navbar:
    show_language_switcher: true
    show_translations: true
    show_current_language: true
    show_day_night: true
    show_search: true
