# Theme
color: blue
day_night: true

appearance:
  theme_day: minimal
  theme_night: dark

# Header
header:
  navbar:
    show_day_night: true
    show_search: true
    show_logo: true
    highlight_active_link: true
    show_translations: true
    show_language: true

# Sections to show
sections:
  - posts
